#ifndef SETTINGS_H_INCLUDED
#define SETTINGS_H_INCLUDED

#define WELCOME_BORDER_COLOR 13
#define WELCOME_TEXT_COLOR 10
#define NUMBER_OF_OPTIONS 3
#define BORDER_X_ZERO 30
#define BORDER_Y_ZERO 2
#define BORDER_WIDTH 25
#define BORDER_HEIGHT 25
#define BORDER_COLOR 10

#endif // SETTINGS_H_INCLUDED
